### ISSUE TITLE
My name is not being recognized

### ISSUE THREAD

**Issue by github-contenta** [RasaHQ/starter-pack-rasa-stack#33]
If I say something like this "My name is Lucy" everything works. However, if I just reply "Lucy" after the bot asks for my name, it doesn't understand that as my name. How can I force the next reply to be recognized as certain slot?

**Comment by MetcalfeTom** [comment]
Hi @github-contenta,

Since the bot learns from generalisation, more examples under the `name` intent won't hurt!

Actually within the Rasa framework, the best way to force this behaviour would be write the conversation as a `Form`.  Then you can use a slot mapping to automatically fill the slot, regardless of the intent.

[Here's some info on forms](https://rasa.com/docs/core/slotfilling/#forms-basics)
